Vagrant.configure("2") do |config|

    # Ubuntu 24.04 : bento/xenial64
    # Ubuntu 22.04 : ubuntu/jammy64
    # Ubuntu 20.04 : ubuntu/focal64
    # Ubuntu 18.04 : ubuntu/bionic64
    config.vm.box = "bento/ubuntu-24.04"
    #config.disksize.size = '20GB'
    config.vm.hostname = "booking-system"

    config.vm.network "forwarded_port", guest: 80, host: 8080
    # Change this IP address to one not being used by another VM
    config.vm.network "private_network", ip: "192.168.56.11"

    config.vm.synced_folder "../", "/var/www/booking-system", :owner => "www-data", :group => "vagrant"

    config.vm.provider "virtualbox" do |v|
        v.name = "booking-system"
        v.memory = 2048
        v.cpus = 2

        #v.customize ["modifyvm", :id, "--cpuexecutioncap", "50"]
        v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
        v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    end

    # Provision scripts for example only. Not all boxes will need all these scripts,
    # or you may wish to install other versions of packages. Ensure the packages installed
    # match what you will be installing to the server.
    # As with the server provision scripts, ensure the scripts are bookended with 'start' and 'finish'
    config.vm.provision "shell", path: "./provision-scripts/start.sh", privileged:false

    config.vm.provision "shell", path: "./provision-scripts/upgrade.sh", privileged: true
    config.vm.provision "shell", path: "./provision-scripts/apache.sh", privileged: true

    config.vm.provision "shell", path: "./provision-scripts/mysql-8.sh", privileged: true

    config.vm.provision "shell", path: "./provision-scripts/php-8.sh", privileged: true
    config.vm.provision "shell", path: "./provision-scripts/enable-default-php-environment-version.sh", privileged: true
    config.vm.provision "shell", path: "./provision-scripts/phpunit.sh", privileged: true

    config.vm.provision "shell", path: "./provision-scripts/swapfile.sh", privileged: true
    config.vm.provision "shell", path: "./provision-scripts/composer.sh", privileged: true

    config.vm.provision "shell", path: "./provision-scripts/redis.sh", privileged: true
    config.vm.provision "shell", path: "./provision-scripts/memcached.sh", privileged: true

    config.vm.provision "shell", path: "./provision-scripts/node-nvm-npm.sh", privileged: false

    config.vm.provision "shell", path: "./provision-scripts/mailhog.sh", privileged: true

    config.vm.provision "shell", path: "./provision-scripts/enable-application.sh", privileged: true
    config.vm.provision "shell", path: "./provision-scripts/clean-up.sh", privileged: true
    config.vm.provision "shell", path: "./provision-scripts/start-application.sh", privileged: true
    config.vm.provision "shell", path: "./provision-scripts/finish.sh", privileged:true

end
